# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# R-Script for plotting ratiometric time-series data, retrieved from FIJI
# Created by Joachim Goedhart (@joachimgoedhart), first version 2020
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

require(ggplot2)
require(tidyr)
require(dplyr)
require(magrittr)

#Read the results file generated by FIJI
df_nuclear <- read.csv("LEXY_Results-nuclear.csv")
df_cyto <- read.csv("LEXY-Results-cytoplasmic.csv")

#Split the column 'Label' into three separate columns, using the colon as delimiter
df_split_nuclear <- df_nuclear %>% separate(Label,c("filename", "Sample","Number"),sep=':')
df_split_cyto <- df_cyto %>% separate(Label,c("filename", "Sample","Number"),sep=':')

#Rename the column with mean intensity
df_split_nuclear <- df_split_nuclear %>% rename('Mean_nucleus'='Mean')
df_split_cyto <- df_split_cyto %>% rename('Mean_cyto'='Mean')

#Unite the two dataframes
df <- full_join(df_split_cyto, df_split_nuclear, by = c("filename","Sample","Slice"))

#Clean
df <- df %>% select(filename, Sample, Slice, Mean_cyto, Mean_nucleus)

#Normalization (here only on first time point)
df <- df %>% group_by(Sample) %>% mutate(norm_cyto=Mean_cyto/mean(Mean_cyto[1:1]),
                                         norm_nuc=Mean_nucleus/mean(Mean_nucleus[1:1]))

#Calculate ratio
df <- df %>% mutate(ratio=norm_nuc/norm_cyto)


#Plot
ggplot(data=df, aes(x=Slice, y=ratio, color=Sample))+geom_point()
